services:
  # mysql数据库
  env_db:
    image: "mysql:8.0.41"
    container_name: env_db
    restart: on-failure:3
    networks:
      - env_net
    ports:
      - "3306:3306"
    volumes:
      # 数据目录挂载
      - ./mysql/data/mysql:/var/lib/mysql
      # 日志目录挂载
      - ./mysql/data/logs:/var/log/mysql
      # 备份目录挂载
      - ./mysql/data/backup:/data/backup
      # 初始SQL文件挂载
      - ./mysql/init:/docker-entrypoint-initdb.d
      # 配置文件挂载
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: "tidy@55555"
      MYSQL_DATABASE: "simple_tidy"
      MYSQL_USER: "tidy"
      MYSQL_PASSWORD: "5faith@55555"

  env_redis:
    image: "redis:7.4.2"
    container_name: env_redis
    restart: on-failure:3
    networks:
      - env_net
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  env_nacos:
    image: nacos/nacos-server:2.0.2
    container_name: env_nacos
    restart: on-failure:3
    networks:
      - env_net
    ports:
      - "8848:8848"
    environment:
      MODE: "standalone"
    volumes:
      - ~/nacos/conf/application.properties:/home/nacos/init.d/custom-config/application.properties
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/health"] # 健康检查命令
      # 检查间隔时间
      interval: 30s
      # 超时时间
      timeout: 10s
      # 失败重试次数
      retries: 3
      # 容器启动后等待多久开始第一次健康检查
      start_period: 10s

  env_nginx:
    image: nginx:1.26.3
    container_name: env_nginx
    restart: on-failure:3
    networks:
      - env_net
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
# env网络
networks:
  env_net:
    driver: bridge